[package]
name = "intiface_engine_flutter_bridge"
version = "1.0.6"
authors = ["Nonpolynomial Labs, LLC <kyle@nonpolynomial.com>"]
description = "Rust-Flutter bridge for IntifaceEngine" 
license = "BSD-3-Clause"
homepage = "http://intiface.com"
readme = "README.md"
edition = "2021"
exclude = [".vscode/**"]

[dependencies]
intiface-engine = "1.4.5"
# intiface-engine = { path = "../../intiface-engine" }
# THIS MUST ALWAYS MATCH THE VERSION USED BY INTIFACE ENGINE
buttplug = { path = "/home/nabos/clones/buttplug/buttplug" }
# buttplug = "7.1.6"
flutter_rust_bridge = "1.82.1"
log = "0.4.20"
lazy_static = "1.4.0"
once_cell = "1.18.0"
tokio = { version = "1.32.0", features = ["rt", "tracing"] }
anyhow = "1.0.75"
# THIS VERSION ABSOLUTELY, POSITIVELY MUST MATCH WHATEVER BUTTPLUG LINKS, OTHERWISE THERE WILL BE
# STATIC MISALIGNMENT AND YOU DO NOT WANT TO SPEND ANOTHER 3 DAYS DEBUGGING THAT.
# btleplug = { path = "../../btleplug" }
btleplug = "0.11.1"
thiserror = "1.0.49"
getset = "0.1.2"
serde = "1.0.188"
serde_json = "1.0.107"
async-trait = "0.1.73"
futures = "0.3.28"
tracing = "0.1.37"
tracing-futures = "0.2.5"

[target.'cfg(target_os = "android")'.dependencies]
# THESE VERSIONS ABSOLUTELY, POSITIVELY MUST MATCH WHATEVER BUTTPLUG LINKS, OTHERWISE THERE WILL BE
# STATIC MISALIGNMENT AND YOU DO NOT WANT TO SPEND ANOTHER 3 DAYS DEBUGGING THAT.
jni = "0.19.0"
jni-utils = "0.1.1"
openssl-sys = {version = "0.9.93", features=["vendored"]}

[lib]
crate-type = ["staticlib", "cdylib"]

[build-dependencies]
flutter_rust_bridge_codegen = "1.82.1"
