name: Intiface Central Build
on: 
  push:
    branches:
      - main
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
      - run: |
         sudo apt-get update -y
         sudo apt-get install -y ninja-build libudev-dev libgtk-3-dev
      - run: flutter config --enable-linux-desktop
        name: flutter config
      - run: flutter build linux --release --dart-define="SENTRY_DSN=${{ secrets.SENTRY_DSN }}"
        name: flutter build
      - name: Zip Release
        run: zip -r intiface-central-linux-x64.zip build/linux/x64/release/bundle
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: linux-zip
          path: ./intiface-central-linux-x64.zip
